# Generated by Django 4.2 on 2025-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('working_hours', models.CharField(max_length=50, verbose_name='Рабочий график')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
